/* Generated By:JavaCC: Do not edit this line. converterConstants.java */
package code;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface converterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 4;
  /** RegularExpression Id. */
  int img = 5;
  /** RegularExpression Id. */
  int header = 6;
  /** RegularExpression Id. */
  int para = 7;
  /** RegularExpression Id. */
  int url = 8;
  /** RegularExpression Id. */
  int decorated_text = 9;
  /** RegularExpression Id. */
  int text = 10;
  /** RegularExpression Id. */
  int color = 11;
  /** RegularExpression Id. */
  int font = 12;
  /** RegularExpression Id. */
  int link = 13;
  /** RegularExpression Id. */
  int sentence = 14;
  /** RegularExpression Id. */
  int quote = 15;
  /** RegularExpression Id. */
  int alphanumeric = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"ADD\"",
    "\"IMAGE WITH SOURCE\"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"AND\"",
    "\"WITH TEXT\"",
    "\"WITH COLOR\"",
    "\"WITH FONT\"",
    "\"WITH LINK\"",
    "<sentence>",
    "\"\\\"\"",
    "<alphanumeric>",
  };

}
